### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by guilherme-gjv** [guilherme-gjv/nodejs-estudos#1]
https://github.com/guilherme-gjv/nodejs-estudos/blob/cbe97f34b4005074e0cff0e2dc3bca3f8c07a266/app.js#L17

![errito](https://user-images.githubusercontent.com/83377948/132247747-1b782b65-9dc1-41f4-a038-4ded170838f5.JPG)

![errito2](https://user-images.githubusercontent.com/83377948/132247757-350f941a-da5b-4c06-9e99-81baff7dcbca.JPG)

**Comment by guilherme-gjv** [comment]
[tá na branch projeto final]

**Comment by guilherme-gjv** [comment]
## Isso não funcionou :heart_eyes: 
![errito3](https://user-images.githubusercontent.com/83377948/132256022-9b1bfeb7-d515-4e10-b199-3a7e1d951cca.JPG)

**Comment by duardoqueiroz** [comment]
https://github.com/guilherme-gjv/nodejs-estudos/issues/1#issue-989338104

Você deu um npm install express-handlebars?
Na hora de importar vc tem que dar um require("express-handlebars"), como dito no comentário do vídeo

**Comment by guilherme-gjv** [comment]
vou tentar dnv aqui

**Comment by guilherme-gjv** [comment]
## MT OBRIGADO <3 KKKKKKKKK 
esse bicho de pirraça, ja tinha dado o npm install. Agr foi, vlw

**Comment by duardoqueiroz** [comment]
agora mama o pai e fecha a issue glub

Em seg, 6 de set de 2021 10:48 PM, Guilherme de Jesus <
***@***.***> escreveu:
